
########################################
# LANDING
########################################
[landing]
id = "landing"
title = "Welcome"
body = """
My name's Jamie, and I'm a developer of things. While my experience generally lies in desktop applications and backend web development, my passion is more general: I like exploiting a computer's ability to do things for me.

I'm a third-year CIS student at UFV. Todo: more personal hook. If interested, there's a whole section [about me](#) below.

[Projects](#) - Check out some of my recent projects.

[Github](https://github.com/jamiesyme) - Browse all of my public projects.

[Contact](#) - Let's chat!
"""


########################################
# PROJECTS
########################################
[projects]
id = "projects"
title = "Projects"

[projects.0]
details = """
I developed Minfo because I was tired of my default, ugly status bar sitting at the bottom of my desktop. I tried customizing it, but it just never felt like it belonged. I tried Conky as well, which was a lot more flexible, but it still didn't behave how I wanted. So, I decided to write something custom.

My old status bar was always visible and always consuming space, but I only ever needed it periodically. Minfo, on the other hand, is hidden about 95% of the time, which means all of my apps can run fullscreen without any distractions. When I need to see the time or some other info, I can press a key (configured in my i3 configuration file) to toggle the window on or off.

To achieve this, I split Minfo into two separate apps: the server (minfo) and the client (minfo-msg). The server is launched on startup, and then the client can be used either from a terminal, or it can be bound to keys in your window manager configuration. The IPC is done over a TCP socket; I could change this to a UNIX domain socket, but TCP works fine for now.

The code was split into a few different components:
+ Surface - wraps all of the Xlib functionality
+ Radio - wraps all of the socket functionality
+ Hub - manages modules and any drawing that's done, as well as manages the Surface
+ Module - a unit of info to be rendered (examples: time module, audio module, etc.)

The goal behind the design of the code was to make it as easy as possible to implement new types of modules. As an example, here are the [header](https://github.com/jamiesyme/minfo/blob/master/src/audio-module.h) and [source](https://github.com/jamiesyme/minfo/blob/master/src/audio-module.c) files for the audio module. The header contains a single function declaration, and the source file is a little over 100 lines long. While LoC isn't the best metric for complexity, it gives a rough idea.
"""
stack = ["C",
         "Xlib",
         "Cairo/Pango",
         "Make"]
screenshots = ["img/minfo-screen-1.png",
               "img/minfo-screen-2.jpg"]
summary = """
Minfo is a lightweight status hub for the X Window System on Linux. It's goal is to provide easy access to basic info like the time and date, while remaining as unintrusive as possible."""
title = "Minfo"
when = "Jan '17 - Present"
[[projects.0.where]]
text = "Github"
url = "https://github.com/jamiesyme/minfo"

[projects.1]
details = """
TODO: write description.
"""
stack = ["JavaScript",
         "React",
         "Node.js",
         "Yarn",
         "Babel"]
screenshots = ["", ""]
summary = """
[jamiesyme.com](localhost:8080) is my online portfolio. It's goal is to showcase my recent work, to tell employers a little about who I am, and to provide a means of contact."""
title = "jamiesyme.com"
when = "Feb '17 - Present"
[[projects.1.where]]
text = "jamiesyme.com"
url = "localhost:8080"
[[projects.1.where]]
text = "Github"
url = "https://github.com/jamiesyme/portfolio"

[projects.2]
details = """
Inspiration for this rendering engine came from the [original Doom game](https://en.wikipedia.org/wiki/Doom_%281993_video_game%29), which used a similar technique to render 3D graphics on far less powerful hardware. The final result, however, is more analogous to [Wolfenstein 3D](https://en.wikipedia.org/wiki/Wolfenstein_3D). 

My intention of this project wasn't to create a super efficient rendering engine to be used in actual games, but rather to explore how you could render a 3D environment without rasterization or ray tracing. As a result, I discovered that the technique is similar to ray tracing, though 3D graphics enthusiasts would probably classify it as ray casting.

Features:
+ First-person navigation using keyboard controls
+ Level defined as 2D array of tiles
+ Texture-mapping based on tile-type
+ Reflection with varying opacity
+ You can see yourself in the mirror!

In the end, I was left with a pure JavaScript implementation capable of running at a decent framerate on modern hardware, and I quenched my thirst of wanting to figure out how games ran before rasterization and GPUs blew up. If I were to do this project again (which I likely will in the future), I would love to play around with multi-leveled rendering, as well as lighting.
"""
stack = ["JavaScript"]
screenshots = ["img/jdoom-screen-1.png",
               "img/jdoom-screen-2.png",
               "img/jdoom-screen-3.jpg"]
summary = """
JDoom is a 3D ray casting rendering demo. It uses the player's horizontal position and rotation within a 2D grid of walls to simulate a 3D environment."""
title = "JDoom"
when = "Oct '15 - Nov '15"
[[projects.2.where]]
text = "Github"
url = "https://github.com/jamiesyme/JDoom"


########################################
# ABOUT
########################################
[about]
id = "about"
title = "About"
body = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sapien nunc, ultricies eget turpis sed, dapibus tempus libero. Vestibulum in sem velit. Donec sed urna quis tellus rhoncus imperdiet. Integer interdum pretium purus at molestie. Cras et nibh quis mauris scelerisque mollis quis quis risus. Curabitur porta, nulla sed molestie volutpat, nisi arcu varius ipsum, semper ullamcorper ipsum libero vel leo. Mauris sit amet condimentum mauris. Etiam ut sapien ut urna ultricies ultrices.

Duis eget imperdiet lorem. Nullam a tortor lacinia, maximus sapien finibus, lobortis mauris. Vivamus efficitur tincidunt mi ac lacinia. Nulla convallis, neque eu pharetra consectetur, purus nisl rhoncus quam, vel interdum risus nisi vitae leo. Etiam a dui nec orci finibus viverra sit amet in urna. Donec dapibus ligula felis, vel posuere arcu ultricies eu. In fermentum aliquet cursus. Maecenas consequat mauris nec velit molestie elementum. Aliquam sodales enim pharetra quam tincidunt condimentum id vitae enim.

Aliquam at nunc venenatis, aliquam nisl at, dictum lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ante justo, pulvinar nec faucibus a, porta eu sapien. Mauris consectetur vehicula ipsum, nec rutrum ligula fermentum vel. Morbi risus dui, elementum ut feugiat sit amet, suscipit sit amet nulla. Vestibulum eu tincidunt sapien, vitae lobortis felis.
"""


########################################
# CONTACT
########################################
[contact]
id = "contact"
title = "Contact"
body = """
Whether you have a question about one of my projects, or you'd like to offer an employment opportunity for this summer, I'd love to hear from you!

You can contact me at [jamie@jamiesyme.com](mailto:jamie@jamiesyme.com).

Alternatively, feel free to use the contact form below.
"""